<?php if (!is_null($data) && $data !== array()): ?>
    <dt><?= $dataName ?></dt>
    <dd>
        <?php if (is_array($data)): ?>
                <?php if (empty($json)): ?>
                    <?php $this->partial('partials/details/data/array', array('data' => $data)); ?>
                <?php else: ?>
                    <?php $this->partial('partials/details/data/json', array('data' => $data)); ?>
                <?php endif; ?>
        <?php else: ?>
            <?= nl2br($data) ?></td>
        <?php endif; ?>
    </dd>
<?php endif; ?>
